# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Andrew Mussey"
description: > # this means to ignore newlines until "email:"
   Software Developer at Rackspace, independent videographer (youtube.com/amussey), hobbyist DJ, & a Virginia Tech Hokie.

email: admin@ajama.org
#blog logo
logo: "/assets/images/am_logo.png"
# blog cover
cover: "/assets/images/Microchip_Color.jpg" # cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Andrew Mussey'
author: 'Andrew Mussey'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://amussey.github.io" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/amussey
    desc: Follow me on Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:
    desc:   Connect with me Facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/amussey
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:   bitbucket
    url:    https://bitbucket.org/amussey
    desc:   Fork me on Bitbucket
    share_url:
    share_title:
    share_link:

  - icon:   youtube
    url:    https://youtube.com/amussey
    desc:   Subscribe to my channel on YouTube
    share_url:
    share_title:
    share_link:

  - icon:	google-plus
    url:	"https://google.com/+AndrewMussey"
    desc:	Add me on Google+
    share_url:
    share_title:
    share_link:
